# docker-compose config


services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streaming_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=streaming_db
      - DB_PORT=5432
      - JWT_SECRET=supersecretjwt
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

volumes:
  db-data: